# Generated by Django 5.2.7 on 2025-10-29 12:46

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Біографія')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Місце проживання')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[accounts.models.validate_image_size], verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
            },
        ),
    ]
